language: php

sudo: false

php:
  - 7.2

branches:
  only:
  - develop
  - /^release.*$/
  - master
  - "/^travis\\//"

env: TMPDIR=/tmp

install:
 - phpenv rehash

services:
  - memcached

before_script:
  - phpenv config-rm xdebug.ini || return 0
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then travis_retry composer self-update; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then travis_retry composer install --no-interaction --prefer-source --dev; fi
  
  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then phpenv config-add tests/config.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7" ]]; then phpenv config-add tests/php7_config.ini; fi

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
 - cd tests/
 - php runalltests.php
